version: 1.2.3.0-alpha{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
install:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019 Preview")

    {

    Write-Host "Installing .NET Core 3.0.100-preview-010431 SDK..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-sdk-3.0.100-preview3-010431-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/31b5b67f-b787-4f73-a728-5ec61f10a4de/be6430bcd9a62f610cd9f12f8cc2c736/dotnet-sdk-3.0.100-preview3-010431-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Core 3.0.0-preview3-27503-5 runtime..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-runtime-3.0.0-preview3-27503-5-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/3f05ee2d-5372-43d6-9562-be86632a53d4/1361281426efa7ff206289adb0411f55/dotnet-runtime-3.0.0-preview3-27503-5-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Framework 4.8 Targeting Pack..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\ndp48-devpack-enu.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/9854b5f2-2341-4136-ad7d-1d881ab8d603/e3a011f2a41a59b086f78d64e1c7a3fc/ndp48-devpack-enu.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green

    }
before_build:
- ps: >-
    nuget sources Add -Name "Generic Roslyn Analyzers" -Source https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json

    cd src/XmlAbstraction/

    nuget restore

    cd ../../

    nuget install OpenCover -Version 4.7.922 -OutputDirectory packages

    nuget install Codecov -Version 1.4.0 -OutputDirectory packages

build:
  project: src/XmlAbstraction/XmlAbstraction.sln
  publish_nuget: true
  # this seems to make tag builds fail now.
  # publish_nuget_symbols: true
  # this warns anyway for netcore and netstandard projects.
  # include_nuget_references: true
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    cd src/XmlAbstraction/

    dotnet test test\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    cd ../../

    packages\Codecov.1.4.0\tools\codecov.exe -f "src/XmlAbstraction/test/coverage.opencover.xml"
deploy:
- provider: NuGet
  api_key:
    secure: w8jKLcMWVbTVBRRjl6k2eoRvajr5DpIB4XBhlEddCvx/9dSnDYbK5J0qXZXazE/E
  on:
    APPVEYOR_REPO_TAG: true
