version: 1.0.0.0-alpha{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  project: XmlAbstraction.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    %UserProfile%\.nuget\packages\opencover\4.6.519\toolsOpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\XmlAbstraction.Test\bin\Release\XmlAbstraction.Test.dll -noshadow" -filter:"+[XmlAbstraction.Test*]*" -output:".\XmlAbstraction_coverage.xml"

    %UserProfile%\.nuget\packages\Codecov\1.1.0\tools\codecov.exe -f ".\XmlAbstraction_coverage.xml"
deploy:
- provider: NuGet
  api_key:
    secure: w8jKLcMWVbTVBRRjl6k2eoRvajr5DpIB4XBhlEddCvx/9dSnDYbK5J0qXZXazE/E
  on:
    APPVEYOR_REPO_TAG: true