version: 1.2.1.0-alpha{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cd src/XmlAbstraction/
- nuget restore
- cd ../../
- nuget install OpenCover -Version 4.6.519 -OutputDirectory packages
- nuget install Codecov -Version 1.1.0 -OutputDirectory packages
build:
  project: src/XmlAbstraction/XmlAbstraction.sln
  publish_nuget: true
  publish_nuget_symbols: true
  # this warns anyway for netcore and netstandard projects.
  # include_nuget_references: true
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    cd src/XmlAbstraction/

    dotnet test XmlAbstraction.Test\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    cd ../../

    packages\Codecov.1.1.0\tools\codecov.exe -f "src/XmlAbstraction/test/coverage.opencover.xml"
deploy:
- provider: NuGet
  api_key:
    secure: w8jKLcMWVbTVBRRjl6k2eoRvajr5DpIB4XBhlEddCvx/9dSnDYbK5J0qXZXazE/E
  on:
    APPVEYOR_REPO_TAG: true