name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: .NET Core setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: warrenbuckley/Setup-Nuget@v1
    - name: .NET Core pre-build
      run: >-
        nuget install OpenCover -Version 4.7.922 -OutputDirectory packages
        
        nuget install Codecov -Version 1.4.0 -OutputDirectory packages
        
    - name: .NET Core build
      run: dotnet build src/XmlAbstraction/XmlAbstraction.sln --configuration Release
    - name: .NET Core test
      run: >-
        cd src/XmlAbstraction/
        
        dotnet test test\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        
        cd ../../
        
        packages\Codecov.1.4.0\tools\codecov.exe -f "src/XmlAbstraction/test/coverage.opencover.xml"
