name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: .NET Core setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: warrenbuckley/Setup-Nuget@v1
    - name: .NET Core pre-build
      run: dotnet tool install --global Codecov.Tool
    - name: .NET Core build
      run: dotnet build src/XmlAbstraction/XmlAbstraction.sln --configuration Release
    - name: .NET Core test
      env: # Or as an environment variable
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: >-
        cd src/XmlAbstraction/
        
        dotnet test test\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        
        cd ../../
        
        codecov -t $env:CODECOV_TOKEN -f "src/XmlAbstraction/test/coverage.opencover.xml"
        
    # experiment with uploading the *.nupkgs.
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v1.0.0
    #   with:
        # Artifact name
    #     name: '*.nupkg'
        # Directory containing files to upload
    #     path: src\XmlAbstraction\src\bin\Any CPU\Release
