name: .NET Core (build & publish pre-release)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: .NET core build
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 5.0.100-preview.4.20202.8
    - name: .NET Core pre-build
      run: dotnet tool install --global Codecov.Tool
    - name: .NET Core build
      run: dotnet build src/XmlAbstraction/XmlAbstraction.sln --configuration Release
    - name: .NET Core test
      env: # Or as an environment variable
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: >-
        cd src/XmlAbstraction/
        
        dotnet test test\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        
        cd ../../
        
        codecov -t $env:CODECOV_TOKEN -f "src/XmlAbstraction/test/coverage.opencover.xml"

    - name: Publish Pre-release
      id: publish_nuget
      uses: rohith/publish-nuget@v2.4.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/XmlAbstraction/src/XmlAbstraction.csproj
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
